### ISSUE TITLE
Show chosen filters + option to remove them

### ISSUE THREAD

**Issue by anarhitetka** [kolaroski/tango-music#30]
Decide where to show the chosen filters that the user checked from the sub-menus of the advanced search bar 
and display them with X to remove them

![Screenshot_1](https://user-images.githubusercontent.com/68745804/177144770-a3eba6b5-c179-440a-87e4-f7adafe02b6e.png)

**Comment by kolaroski** [comment]
Add cards based on the current selected filter.
